services:

  postgres:
    image: postgres:18
    container_name: library-db-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # See README.md
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes: 
  pgdata: