SELECT DISTINCT branchid, branchname
FROM temp_raw_data;

CREATE TABLE branches (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

INSERT INTO branches (id, name)
SELECT DISTINCT branchid, branchname
FROM temp_raw_data
ORDER BY branchid;