SELECT bookID, author
FROM temp_raw_data
WHERE author !~ '^[A-Za-z]+ [A-Za-z]+$';

SELECT bookID, author
FROM temp_raw_data
WHERE author ~ '^((Mr.)|(Mrs.)|(Dr.)) [A-Za-z]+ [A-Za-z]+';

SELECT
    bookID,
    author,
    ARRAY_TO_STRING((STRING_TO_ARRAY(author, ' '))[2:], ' ')
FROM temp_raw_data
WHERE author ~ '^((Mr\.)|(Mrs\.)|(Dr\.)) [A-Za-z]+ [A-Za-z]+';

UPDATE temp_raw_data
SET author = ARRAY_TO_STRING((STRING_TO_ARRAY(author, ' '))[2:], ' ')
WHERE author ~ '^((Mr\.)|(Mrs\.)|(Dr\.)) [A-Za-z]+ [A-Za-z]+';

SELECT
    bookID,
    author,
    ARRAY_TO_STRING((STRING_TO_ARRAY(author, ' '))[1:2], ' ')
FROM temp_raw_data
WHERE author !~ '^[A-Za-z]+ [A-Za-z]+$';

UPDATE temp_raw_data
SET author = ARRAY_TO_STRING((STRING_TO_ARRAY(author, ' '))[1:2], ' ')
WHERE author !~ '^[A-Za-z]+ [A-Za-z]+$';

SELECT author, ARRAY_AGG(bookID)
FROM temp_raw_data
GROUP BY author
HAVING COUNT(*) > 1;

SELECT DISTINCT 
    author,
    ARRAY_TO_STRING((STRING_TO_ARRAY(author, ' '))[1:1], ' ') AS first,
    ARRAY_TO_STRING((STRING_TO_ARRAY(author, ' '))[2:2], ' ') AS last
FROM temp_raw_data
LIMIT 30;

CREATE TABLE authors (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL
);

INSERT INTO authors (first_name, last_name)
SELECT DISTINCT
    ARRAY_TO_STRING((STRING_TO_ARRAY(author, ' '))[1:1], ' ') AS first,
    ARRAY_TO_STRING((STRING_TO_ARRAY(author, ' '))[2:2], ' ') AS last
FROM temp_raw_data;


CREATE TABLE authors (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL
);

INSERT INTO authors (first_name, last_name)
SELECT first_name, last_name
FROM old_authors;