CREATE TABLE genres (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

INSERT INTO genres (name)
SELECT DISTINCT genre
FROM temp_raw_data;

CREATE TABLE genres (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

INSERT INTO genres (name)
SELECT name
FROM old_genres;