/* Create table representing individual book rentals. */
CREATE TABLE checkouts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id integer NOT NULL,
    book_id integer NOT NULL,
    branch_id integer NOT NULL,
    checkout_date date NOT NULL,
    return_date date,
    CONSTRAINT fk_members
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_book
        FOREIGN KEY (book_id)
        REFERENCES books(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(id)
        ON DELETE CASCADE
);

/* Preview an individual borrow
SELECT 
    m.id AS member_id,
    t.bookID AS book_id,
    t.branchID AS branch_id,
    TO_DATE(borrowdate, 'YYYY-MM-DD') AS checkout_date,
    TO_DATE(returndate, 'YYYY-MM-DD') AS return_date
FROM temp_raw_data t
JOIN members m
ON 
    m.first_name = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:1], ' ') AND
    m.last_name = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:2], ' ')
LIMIT 10;
*/

INSERT INTO checkouts (member_id, book_id, branch_id, checkout_date, return_date)
SELECT 
    m.id AS member_id,
    t.bookID AS book_id,
    t.branchID AS branch_id,
    TO_DATE(borrowdate, 'YYYY-MM-DD') AS checkout_date,
    TO_DATE(returndate, 'YYYY-MM-DD') AS return_date
FROM temp_raw_data t
JOIN members m
ON 
    m.first_name = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:1], ' ') AND
    m.last_name = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:2], ' ');
    