/*
This script was used to record the process of importing some data from the CSV file into the designed database schema.
Some SQL command were purely exploratory, where others perform that actual steps to import the data.
The former kind of commands will be commented out; the latter will not. All will have descriptinos in comment form.
*/

/* Joins authors table to temp data to preview matching temp data records with author IDs.
SELECT t.bookID, t.title, t.author, a.id AS author_id, a.first_name, a.last_name
FROM temp_raw_data t
LEFT JOIN authors a
ON 
    a.first_name = (STRING_TO_ARRAY(t.author, ' '))[1] AND
    a.last_name = (STRING_TO_ARRAY(t.author, ' '))[2]
LIMIT 10;
*/

/* Joins genres table to temp data to preview matching temp data records with genre IDs.
SELECT t.bookID, t.title, t.genre, g.id, g.name
FROM temp_raw_data t
LEFT JOIN genres g
ON t.genre = g.name
LIMIT 100;
*/

/* Previews matching temp data records with author and genre IDs.
SELECT t.bookID, t.title, a.id AS author_id, g.id AS genre_id
FROM temp_raw_data t
LEFT JOIN authors a
ON 
    a.first_name = (STRING_TO_ARRAY(t.author, ' '))[1] AND
    a.last_name = (STRING_TO_ARRAY(t.author, ' '))[2]
LEFT JOIN genres g
ON t.genre = g.name
LIMIT 10;
*/

/* Creates new books table. */
CREATE TABLE books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,         
    author_id INTEGER DEFAULT 0,
    genre_id INTEGER DEFAULT 0,
    CONSTRAINT fk_author
        FOREIGN KEY (author_id)
        REFERENCES authors(id)
        ON DELETE SET DEFAULT,
    CONSTRAINT fk_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres(id)
        ON DELETE SET DEFAULT
);

/* Inserts book information from temp data into books table, using foreign keys to connect to author and genre tables. */
INSERT INTO books (id, title, author_id, genre_id)
SELECT t.bookID, t.title, a.id, g.id
FROM temp_raw_data t
LEFT JOIN authors a
ON 
    a.first_name = (STRING_TO_ARRAY(t.author, ' '))[1] AND
    a.last_name = (STRING_TO_ARRAY(t.author, ' '))[2]
LEFT JOIN genres g
ON t.genre = g.name;