/*
This script was used to record the process of importing some data from the CSV file into the designed database schema.
Some SQL command were purely exploratory, where others perform that actual steps to import the data.
The former kind of commands will be commented out; the latter will not. All will have descriptinos in comment form.
*/

/* List all distinct branches. 
SELECT DISTINCT branchid, branchname
FROM temp_raw_data;
*/

/* Create new table for branches. */
CREATE TABLE branches (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

/* Insert datafrom temp data into new branches table. */
INSERT INTO branches (id, name)
SELECT DISTINCT branchid, branchname
FROM temp_raw_data
ORDER BY branchid;