SELECT t.bookID, t.title, t.author, a.id AS author_id, a.first_name, a.last_name
FROM temp_raw_data t
LEFT JOIN authors a
ON 
    a.first_name = (STRING_TO_ARRAY(t.author, ' '))[1] AND
    a.last_name = (STRING_TO_ARRAY(t.author, ' '))[2]
LIMIT 10;

SELECT t.bookID, t.title, t.genre, g.id, g.name
FROM temp_raw_data t
LEFT JOIN genres g
ON t.genre = g.name
LIMIT 100;

SELECT t.bookID, t.title, a.id AS author_id, g.id AS genre_id
FROM temp_raw_data t
LEFT JOIN authors a
ON 
    a.first_name = (STRING_TO_ARRAY(t.author, ' '))[1] AND
    a.last_name = (STRING_TO_ARRAY(t.author, ' '))[2]
LEFT JOIN genres g
ON t.genre = g.name
LIMIT 10;

SELECT COUNT(*)
FROM (
    SELECT t.bookID, t.title, a.id AS author_id, g.id AS genre_id
    FROM temp_raw_data t
    LEFT JOIN authors a
    ON 
        a.first_name = (STRING_TO_ARRAY(t.author, ' '))[1] AND
        a.last_name = (STRING_TO_ARRAY(t.author, ' '))[2]
    LEFT JOIN genres g
    ON t.genre = g.name
);

CREATE TABLE books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,         
    author_id INTEGER DEFAULT 0,
    genre_id INTEGER DEFAULT 0,
    CONSTRAINT fk_author
        FOREIGN KEY (author_id)
        REFERENCES authors(id)
        ON DELETE SET DEFAULT,
    CONSTRAINT fk_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres(id)
        ON DELETE SET DEFAULT
);

INSERT INTO books (id, title, author_id, genre_id)
SELECT t.bookID, t.title, a.id, g.id
FROM temp_raw_data t
LEFT JOIN authors a
ON 
    a.first_name = (STRING_TO_ARRAY(t.author, ' '))[1] AND
    a.last_name = (STRING_TO_ARRAY(t.author, ' '))[2]
LEFT JOIN genres g
ON t.genre = g.name;