/*
This script was used to record the process of importing some data from the CSV file into the designed database schema.
Some SQL command were purely exploratory, where others perform that actual steps to import the data.
The former kind of commands will be commented out; the latter will not. All will have descriptinos in comment form.
*/

/* Count number of names associated with each borrower ID (more than one, for some reason).
SELECT borrowerid, COUNT(DISTINCT borrowername)
FROM temp_raw_data
GROUP BY borrowerid;
*/

/* List data for all borrows associated with a barrower_id of 1.
SELECT *
FROM temp_raw_data
WHERE borrowerid = 1;
*/

/* List borrower names associated with more than one barrow.
SELECT borrowername
FROM temp_raw_data
GROUP BY borrowername
HAVING COUNT(*) > 1;
*/

/* It is clear that the IDs do not uniquely identify borrowers. These IDs will therefore be discarded. */

/* List borrower names which do not fit with a "Firstname Lastname" foramt.
SELECT bookID, borrowername
FROM temp_raw_data
WHERE borrowername !~ '^[A-Za-z]+ [A-Za-z]+$';
*/

/* Preview the removal of prefixes from borrower names which have them. 
SELECT
    bookID,
    borrowername,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:], ' ')
FROM temp_raw_data
WHERE borrowername ~ '^((Mr\.)|(Mrs\.)|(Dr\.)) [A-Za-z]+ [A-Za-z]+';
*/

/* Remove prefixes from borrower names who have them. */
UPDATE temp_raw_data
SET borrowername = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:], ' ')
WHERE borrowername ~ '^((Mr\.)|(Mrs\.)|(Dr\.)) [A-Za-z]+ [A-Za-z]+';

/* Preview removing suffixes from borrower names who still do not follow a "Firstname Lastname" format.
SELECT
    bookID,
    borrowername,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:2], ' ')
FROM temp_raw_data
WHERE borrowername !~ '^[A-Za-z]+ [A-Za-z]+$';
*/

/* Remove suffixes from borrower names who have them. */
UPDATE temp_raw_data
SET borrowername = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:2], ' ')
WHERE borrowername !~ '^[A-Za-z]+ [A-Za-z]+$';

/* Confirm that all names now follow a "Firstname Lastname" format.
SELECT COUNT(*)
FROM temp_raw_data
WHERE borrowername !~ '^[A-Za-z]+ [A-Za-z]+$';
*/

/*Preview extracting first and last names from borrowername column. 
SELECT DISTINCT 
    borrowername,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:1], ' ') AS first,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:2], ' ') AS last
FROM temp_raw_data
LIMIT 30;
*/

/* Create new members table. */
CREATE TABLE members (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL
);

/* Import members into new tables. */
INSERT INTO members (first_name, last_name)
SELECT DISTINCT
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:1], ' ') AS first,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:2], ' ') AS last
FROM temp_raw_data;