SELECT borrowerid, COUNT(DISTINCT borrowername)
FROM temp_raw_data
GROUP BY borrowerid;

SELECT *
FROM temp_raw_data
WHERE borrowerid = 1;

SELECT borrowername
FROM temp_raw_data
GROUP BY borrowername
HAVING COUNT(*) > 1;

SELECT bookID, borrowername
FROM temp_raw_data
WHERE borrowername !~ '^[A-Za-z]+ [A-Za-z]+$';

SELECT
    bookID,
    borrowername,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:], ' ')
FROM temp_raw_data
WHERE borrowername ~ '^((Mr\.)|(Mrs\.)|(Dr\.)) [A-Za-z]+ [A-Za-z]+';

UPDATE temp_raw_data
SET borrowername = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:], ' ')
WHERE borrowername ~ '^((Mr\.)|(Mrs\.)|(Dr\.)) [A-Za-z]+ [A-Za-z]+';

SELECT
    bookID,
    borrowername,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:2], ' ')
FROM temp_raw_data
WHERE borrowername !~ '^[A-Za-z]+ [A-Za-z]+$';

UPDATE temp_raw_data
SET borrowername = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:2], ' ')
WHERE borrowername !~ '^[A-Za-z]+ [A-Za-z]+$';

SELECT DISTINCT 
    borrowername,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:1], ' ') AS first,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:2], ' ') AS last
FROM temp_raw_data
LIMIT 30;

CREATE TABLE customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL
);

INSERT INTO customers (first_name, last_name)
SELECT DISTINCT
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:1], ' ') AS first,
    ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:2], ' ') AS last
FROM temp_raw_data;

SELECT COUNT(*)
FROM (
    SELECT first_name, last_name
    FROM customers
    GROUP BY first_name, last_name
);
