CREATE TABLE checkouts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL,
    book_id integer NOT NULL,
    branch_id integer NOT NULL,
    checkout_date date NOT NULL,
    return_date date,
    CONSTRAINT fk_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_book
        FOREIGN KEY (book_id)
        REFERENCES books(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_branch
        FOREIGN KEY (branch_id)
        REFERENCES branches(id)
        ON DELETE CASCADE
);

SELECT 
    c.id AS customer_id,
    t.bookID AS book_id,
    t.branchID AS branch_id,
    TO_DATE(borrowdate, 'YYYY-MM-DD') AS checkout_date,
    TO_DATE(returndate, 'YYYY-MM-DD') AS return_date
FROM temp_raw_data t
JOIN customers c
ON 
    c.first_name = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:1], ' ') AND
    c.last_name = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:2], ' ')
LIMIT 10;

INSERT INTO checkouts (customer_id, book_id, branch_id, checkout_date, return_date)
SELECT 
    c.id AS customer_id,
    t.bookID AS book_id,
    t.branchID AS branch_id,
    TO_DATE(borrowdate, 'YYYY-MM-DD') AS checkout_date,
    TO_DATE(returndate, 'YYYY-MM-DD') AS return_date
FROM temp_raw_data t
JOIN customers c
ON 
    c.first_name = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[1:1], ' ') AND
    c.last_name = ARRAY_TO_STRING((STRING_TO_ARRAY(borrowername, ' '))[2:2], ' ');
    